# -*- coding: utf-8 -*-
"""mock test

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMgGaKzE1zEyc-GI3mDu4_BRYdUEja8g
"""

#1solution

def get_even_numbers(numbers):
    return [num for num in numbers if num % 2 == 0]

#2solution

import time

def timer(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Execution time: {execution_time} seconds")
        return result
    return wrapper

@timer
def my_function():

    time.sleep(2)

my_function()

#3solution

def calculate_mean(numbers):
    total = sum(numbers)
    count = len(numbers)
    mean = total / count
    return mean

data = [10, 15, 20, 25, 30]
mean_value = calculate_mean(data)
print("Mean:", mean_value)

#4solution

from scipy import stats

def perform_hypothesis_test(sample1, sample2):
    t_statistic, p_value = stats.ttest_ind(sample1, sample2)
    return p_value

sample1 = [5, 10, 15, 20, 25]
sample2 = [10, 20, 30, 40, 50]
p_value = perform_hypothesis_test(sample1, sample2)
print("P-value:", p_value)

